// frontend/src/routes/login/+page.svelte
<h1>Log in</h1>

<main class="w-96">
    <form action="/login" method="post" class="m-auto ">
        <div>
            <label for="email" class="block mb-2 text-sm font-medium"
                >Email:</label
            >
            <input
                type="email"
                id="email"
                name="email"
                class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                required
            />
        </div>
        <div>
            <label for="confirm_password" class="block mb-2 text-sm font-medium"
                >Password:</label
            >
            <input
                type="password"
                id="password"
                name="_password"
                minlength="8"
                class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                required
            />
        </div>
        <input
            type="submit"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold rounded py-2 px-4"
            value="Sign in"
        />
    </form>
</main>

// v/src/views/Login.vue
<template>
    <form action="views">
        <div class="container">
            <h1>Log in</h1>
            <label for="email">Email</label>
            <input type="text" placeholder="Enter email" name="email" id="email" required>

            <label for="password">Password</label>
            <input type="password" placeholder="Enter password" name="pswd" id="password" required>

        <button type="submit" class="registerbtn">Log in</button>
        </div>
    </form>
</template>

<style scoped>
input[type=text], input[type=password] {
    display: inline-block;
    padding: 10px;
    margin-bottom: 10px;
    width: 100%;
    background-color: #444;
    border: none;
    color: #ddd;
}

form {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, 50%);
}

.registerbtn {
    background-color: #04AA6D;
    color: white;
    width: 100%;
    padding:16px 0;
    margin: 10px 0;
    border: none;
}
</style>
